name: Hello Example
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - name: multiple paths
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: '${{ runner.os }}-${{ hashFiles(''TODO'') }}'
      - uses: actions/checkout@v2
      - run: |
          rustup install nightly
          cargo --version
          docker --version
      - run: >-
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      - run: >-
          sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main"
      - run: |
          sudo apt-get update
          sudo apt-get install -y openssl --allow-unauthenticated
          sudo apt-get install -y libssl-dev --allow-unauthenticated
          sudo apt-get install -y clang-7 --allow-unauthenticated
          sudo apt-get install -y libssl1.1 --allow-unauthenticated
          clang-7 --version
          npm install node
          node --version
          npm install
          sh -c "$(curl -sSfL https://release.solana.com/v1.7.8/install)"
          export PATH=~/.local/share/solana/install/active_release/bin:$PATH
          solana-install info
          solana-keygen new --no-bip39-passphrase
          solana-test-validator --quiet &
          npm run lint
          npm run build:program-rust
          npm run test:program-rust
          cargo test-bpf --manifest-path=./src/program-rust/Cargo.toml
          solana config set --url localhost
          solana program deploy dist/program/helloworld.so
          npm run start
          npm run build:program-c
          solana program deploy dist/program/helloworld.so
          npm run start
